apiVersion: apps/v1
kind: Endpoint
spec:
  requests:
    - description: I serve the path /hello
      method: GET
      sleep: 250
      status_code: 200
      headers:
        content-type: text/html
      raw_body: >
        Hello! We see you discovered how to write a root spec file!<br>
        Click <a href="/hello/world">here</a> to see a json file served by the engine.<br>
        Psst! Did you notice the server slept for 250ms? It's configurable! Read the spec file!
